main: de.carina.thehunter.TheHunter
version: 1.3.4
description: The TheHunter minigame but in a remastered version in kotlin for papermc servers
api-version: 1.19
author: Carina Sophie Schoppe
name: TheHunter-Remaster
commands:
  start:
    description: starts the game
    permission: thehunter.start
    usage: /start
  theHunter:
    description: The base command of the entire minigame
    usage: /theHunter <command> <arguments>
    aliases:
      - th
      - hunter
