/*
 * Copyright Notice for theHunterRemaster Copyright (c) at Carina Sophie Schoppe 2022 File created on 9/26/22, 11:08 PM by Carina Sophie The Latest changes made by Carina Sophie on 9/26/22, 11:06 PM All contents of "ConstantStrings.kt" are protected by copyright. The copyright law, unless expressly indicated otherwise, is at Carina Sophie Schoppe. All rights reserved Any type of duplication, distribution, rental, sale, award, Public accessibility or other use requires the express written consent of Carina Sophie Schoppe.
 */

package de.pixels.thehunter.util.misc

object ConstantStrings {

    const val DOT_POINTS = ".Points"
    const val DOT_DEATHS = ".Deaths"
    const val SNIPER_AMMO: String = "sniper-ammo"
    const val PISTOL_AMMO: String = "pistol-ammo"
    const val RIFLE_AMMO: String = "rifle-ammo"
    val MINIGUN_AMMO: String = "minigun-ammo"
    const val SPAWN_LOCATIONS = "spawn-locations"
    const val COMMAND_PERCENT = "%command%"
    const val GUI_COMMAND = "gui"
    const val START_COMMAND = "start"
    const val STATS_COMMAND = "stats"
    const val TEAM_COMMAND = "team"
    const val SQLITE_PATH = "sqlite-path"
    const val DELETE_COMMAND = "delete"
    const val JOIN_COMMAND = "join"
    const val SETUP_COMMAND = "setup"
    const val LEAVE_COMMAND = "leave"
    const val INVENTORY_COMMAND = "inventory"
    const val PLAYER_NOT_IN_TEAM = "player-not-in-team"
    const val SETTINGS_COMMAND = "settings"
    const val MAP_RESET_COMMAND = "mapreset"
    const val NOT_ENOUGH_ARGUMENTS = "not-enough-arguments"
    const val ARGUMENTS_PERCENT = "%arguments%"
    const val NOT_A_PLAYER = "not-a-player"
    const val CREATE_COMMAND = "create"
    const val GAME_NOT_EXISTS = "game-not-exists"
    const val SELECT_COMMAND = "select"
    const val REMOVE_COMMAND = "remove"
    const val CONFIG_COMMAND = "config"
    const val GAME_PERCENT = "%game%"
    const val COMMAND_NOT_FOUND = "command-not-found"
    const val NO_PERMISSION = "no-permission"
    const val LOBBY_SPAWN = "lobbyspawn"
    const val SPECTATOR_SPAWN = "spectatorspawn"
    const val HEALER_AMOUNT = "healer-amount"
    const val BACK_SPAWN = "backspawn"
    const val POWER_PERCENT = "%power%"
    const val FOOD_RECHARGE = "food-recharge"
    const val PLAYER_PERCENT = "%player%"
    const val END_SPAWN = "endspawn"
    const val GAME_STARTING_IN = "game-starting-in"
    const val DURATION_SPEEDUP = "duration-speedup"
    const val ARENA_CENTER = "arenacenter"
    const val ENDCOUNTDOWN_MESSAGE = "endcountdown-message"
    const val BLOCK_PERCENT = "%block%"
    const val ENDCOUNTDOWN_DURATION = "duration-endcountdown"
    const val GAME_STARTING = "game-starting"
    const val TIME_PERCENT = "%time%"
    const val SIZE_PERCENT = "%size%"
    const val PLAYER_SPAWN = "playerspawn"
    const val KILLER_PERCENT = "%killer%"
    const val PLAYERS_PERCENT = "%players%"
    const val GAME_SPEEDUP = "game-speedup"
    const val INVITE_COMMAND = "invite"
    const val FINISH_COMMAND = "finish"
    const val PLAYER_NOT_IN_GAME = "player-not-in-game"
    const val ACCEPT_COMMAND = "accept"
    const val PROMOTE_COMMAND = "promote"

}
